# Learning the NumPy Library

In [2]:
import numpy as np
np.__version__

'1.23.3'

## Arrays

In [16]:
# integer array
print(np.array([2, 4, 6, 8, 10]))

# upcast array (to float32)
print(np.array([2, np.sqrt(2), 17, 14.9]))

# arrays have a fixed type, inferred from values or set explicityly
print(np.array([2, np.sqrt(2), 17, 14.9], dtype='float64'))

# multidimensional
print(np.array([range(i, i + 4) for i in [1, 2, 3]]))

[ 2  4  6  8 10]
[ 2.          1.41421356 17.         14.9       ]
[ 2.          1.41421356 17.         14.9       ]
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


## Built-in Arrays

In [38]:
print("array of 0's, length 10:", np.zeros(10, dtype=int), end="\n\n")
print("2x3 array of 1's:", np.ones((2, 3), dtype=float), end="\n\n")
print("array of values [0, 30), multiples of 3:", np.arange(0, 30, 3), end="\n\n")
print("array of four values [0, 2], even spaced:", np.linspace(0, 2, 4), end="\n\n")
print("random 3x3 array, values [0, 1):", np.random.random((3, 3)), end="\n\n")
print("random 3x3 array of normally distributed values:", np.random.normal(0, 1, (3, 3)), end="\n\n")
print("random 3x3 array of integer values [0, 10):", np.random.randint(0, 10, (3,3)), end="\n\n")
print("4x4 identity matrix:", np.eye(4), end="\n\n")
print("array from [0, 10):", np.arange(10))

array of 0's, length 10: [0 0 0 0 0 0 0 0 0 0]

2x3 array of 1's: [[1. 1. 1.]
 [1. 1. 1.]]

array of values [0, 30), multiples of 3: [ 0  3  6  9 12 15 18 21 24 27]

array of four values [0, 2], even spaced: [0.         0.66666667 1.33333333 2.        ]

random 3x3 array, values [0, 1): [[0.70388858 0.10022689 0.91948261]
 [0.7142413  0.99884701 0.1494483 ]
 [0.86812606 0.16249293 0.61555956]]

random 3x3 array of normally distributed values: [[ 0.05564534  0.29823817  1.3263859 ]
 [-0.69456786 -0.14963454 -0.43515355]
 [ 1.84926373  0.67229476  0.40746184]]

random 3x3 array of integer values [0, 10): [[9 7 7]
 [5 1 2]
 [2 8 1]]

4x4 identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

array from [0, 10): [0 1 2 3 4 5 6 7 8 9]


## Array Attributes

In [36]:
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=5)
x2 = np.random.randint(10, size=(5, 5))
x3 = np.random.randint(10, size=(5, 5, 5))

# slicing is [start:end:increment]
print("access index 0 of x1:", x1[0])
print("access last value of x1:", x1[-1])
print("access [0][3] value of x2:", x2[0, 3])
print("access slice [2][3:5] of x2:", x2[2, 3:5])

print()

print("x3 dimension:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("x3 dtype:", x3.dtype)
print(f"{x3.nbytes} x {x3.size} = {x3.nbytes}")


## TODO
# we can get copies of arrays with .copy()
# we can reshape arrays with .reshape()
# we can concatenate arrays with np.concatenate()
# we can stack arrays with np.hstack() and np.vstack()
# we can split arrays with np.split(), np.hsplit(), and np.vsplit()

access index 0 of x1: 5
access last value of x1: 7
access [0][3] value of x2: 2
access slice [2][3:5] of x2: [8 1]

x3 dimension: 3
x3 shape: (5, 5, 5)
x3 size: 125
x3 dtype: int64
1000 x 125 = 1000
